Initial Commit of Copper Supply Chain.
uncefact/project-crm pull request #8
Opened 2024-12-12 05:39 UTC by dashkodali

Adding read me section with Critial Integration details for the supply chain.

Adding JSON credentials to be added to the RI's app-config.json.

2024-12-13 00:15 UTC, bblazicevic approved these changes

2024-12-13 00:31 UTC, bblazicevic requested changes
Correct spelling, Smealter to Smelter
Change OrgBook to BC Corporate Registry, ie OrgBook BC doesn't issue the DIA, it would be the issuer 'Office of Registrar' as per BC Corp Registry

2024-12-20 05:21 UTC, PatStLouis requested changes

2024-12-20 05:21 UTC, PatStLouis commented on credentials/copper_mine/dcc_mines_act_permit_mine ordered.json
> +  ],
```suggestion
```
Please remove the proof since the source credential has been changed

2024-12-20 05:21 UTC, PatStLouis commented on credentials/copper_mine/dcc_mines_act_permit_mine ordered.json
> +    "assessorLevel": "3rdParty",
I don't thing a 3rdParty is an appropriate value here

2024-12-20 05:21 UTC, PatStLouis commented on credentials/copper_mine/dcc_mines_act_permit_mine ordered.json
> +    "id": "https://idr.bcmine.pyx.io/01/09359502000034/21/32001",
What is this supposed to resolve to?

2025-01-07 00:23 UTC, onthebreeze commented
merging this for now - because I need to restructure the site a bit.  Please raise any outstanding issues in a separate PR.

2025-01-07 00:29 UTC, merged